# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    working_directory: ~/todo-backend/backend

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      IMAGE_NAME: chrismipi/todo-backend

    steps:
      - checkout:
          path: ~/todo-backend
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: 
          name: Getting Dependancies
          command: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      # run tests!
      - run: 
          name: Running all tests
          command: gradle test -i
      # build the artifact
      - run:
          name: Build the JARS
          command: gradle clean build
      # build the docker image
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
  
  publish-latest:
    environment:
      IMAGE_NAME: chrismipi/todo-backend
    docker:
      - image: circleci/openjdk
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
    version: 2
    build-master:
      jobs:
        - build:
            filters:
              branches:
                only: master
        - publish-latest:
            requires:
              - build
            filters:
              branches:
                only: master